config_entity_access_deny.config:
  title: 'Config Entity Access Deny'
  route_name: config_entity_access_deny.config
  description: 'Configuration for the config entity access deny.'
  parent: system.admin_config_system
