<?php

/**
 * @file
 * Install, update and uninstall functions for Permission Access Deny module.
 */

use Drupal\permission_access_deny\Form\PermissionAccessDenyConfigForm;

/**
 * Implements hook_uninstall().
 */
function permission_access_deny_uninstall() {
  \Drupal::configFactory()
    ->getEditable(PermissionAccessDenyConfigForm::CONFIG_NAME)
    ->clear(PermissionAccessDenyConfigForm::AFFECT_PERMISSION_KEY)
    ->save();
}
